### ISSUE TITLE
semantic mistake

### ISSUE THREAD

**Issue by shundaime** [x3388638/react-grid-carousel#7]
Hi i scan my project with Accessibility Insight and i have an issue with an ul tag that does not contain li tag.
But this ul is generate by your project.
Can you replace by a div ? Because there is no need of such tag here.
Best regards

[Capture d’écran de 2022-01-04 17-10-02](https://user-images.githubusercontent.com/45879577/148088896-bf227812-a6d9-4d50-b575-ab239174a233.png)

**Comment by x3388638** [comment]
Hi @shundaime 
Seems that ul element is not in the carousel component, as you can see the image below
<img width="2211" alt="截圖 2022-01-05 上午10 20 20" src="https://user-images.githubusercontent.com/8147952/148150547-0a26b9e4-1085-448a-ad65-1a5e4eed7dbe.png">

**Comment by shundaime** [comment]
Ok my bad it's in my code
